package entity;
// Generated 17/01/2020 01:21:39 PM by Hibernate Tools 4.3.1



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private long iddetalle;
     private Producto producto;
     private Venta venta;
     private int cantidad;

    public Detalle() {
    }

    public Detalle(long iddetalle, Producto producto, Venta venta, int cantidad) {
       this.iddetalle = iddetalle;
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
    }
   
    public long getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(long iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

}


