package entity;
// Generated 21/01/2020 03:40:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private long idventa;
     private Date fecha;
     private BigDecimal total;
     private Set detalles = new HashSet(0);

    public Venta() {
    }

	
    public Venta(long idventa, Date fecha, BigDecimal total) {
        this.idventa = idventa;
        this.fecha = fecha;
        this.total = total;
    }
    public Venta(long idventa, Date fecha, BigDecimal total, Set detalles) {
       this.idventa = idventa;
       this.fecha = fecha;
       this.total = total;
       this.detalles = detalles;
    }
   
    public long getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(long idventa) {
        this.idventa = idventa;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


